### ISSUE TITLE
Missing call to gb_new()?

### ISSUE THREAD

**Issue by sam-falvo** [ZipCPU/tttt#2]
I see you have defined a function gb_new(), which mallocs a new board.  This function does not appear to be called anywhere in the version I cloned.  (Strangely, it somehow still works.)  Should main() or play_game() create the board before resetting it with gb_new()?  It seems like we should be able to just s/gb_new/gb_reset/ and it should work without further changes.

The reason I'm asking is, my computer does not have an MMU, and if you're relying on MMU behavior in some capacity to auto-initialize or auto-allocate the structure, it will crash spectacularly on my Kestrel hardware.  :)

**Comment by ZipCPU** [comment]
Hi, Sam!  Looks like I haven't been receiving github issue notiications, so sorry for the delay.  Hopefully I've got that fixed now.

In the code, the game board is allocated on the stack in the play_game function in main.cpp.  There's no requirement for an MMU, and indeed I've played it many times without an MMU.

Incidentally, newlib offers malloc() and free() functionality without needing an MMU, and this game depends upon newlib.  That said, I'm still looking forward to adding an MMU to the ZipCPU--it just won't impact this game.

Dan
